### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by louis993546** [louis993546/Android-benchmark#11]
I ended up commenting the shebang and directly specifying where i got the `kotlin` from (sdkman), and now it runs in the Ubuntu WSL on my machine. 

It will probably be the same on a real machine, but just to be safe, get virtualbox and install a linux vm running to try

**Comment by louis993546** [comment]
Error 1: `Caused by: com.android.builder.errors.EvalIssueException: Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.`

Error 1a: If you update to 11, of course now you got it the other way around
`e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

I suppose I will need to split the list into 2, and run `export JAVA_HOME`  for each group

**Comment by louis993546** [comment]
Error 2: `Caused by: java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

**Comment by louis993546** [comment]
Error 3: glide is not compiling
```
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.from(DefaultConfigurableFileCollection.java:152)
	at org.gradle.api.internal.file.DefaultFileOperations.configurableFiles(DefaultFileOperations.java:104)
	at org.gradle.groovy.scripts.DefaultScript.files(DefaultScript.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:130)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:77)
```
